version: '3.8'

networks:
  local:
    driver: bridge

services:
  postgres_db:
    image: postgres:12
    hostname: postgres
    restart: "no"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_management
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - local
    command: [ "postgres", "-c", "log_statement=all", "-c", "max_connections=300" ]
  postgres_ui:
    image: dpage/pgadmin4:8.9
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    expose:
      - 5050
    ports:
      - "5050:80"
    networks:
      - local
    restart: "no"
    depends_on:
      - postgres_db