#---------------------------------------------------------------------
# Spring settings
#---------------------------------------------------------------------
spring:
  profiles:
    active: dev






